### ISSUE TITLE
ini file creation wizzward

### ISSUE THREAD

**Issue by Bankai-true** [LUCIT-Systems-and-Development/unicorn-binance-trailing-stop-loss#10]
### Is your feature request related to a problem? Please describe.

It makes the installation easier

### Describe the solution you'd like.

A wizard that checks the config.ini file is present, if not it must be created. 
If available take over old values? Yes no
If no, create new and all info will be queried and written to the file.
If the profile.ini already exists then ask if you want to overwrite with example profile or if you want to keep the old profile. If not available create with demo data and output info where it is.

**Comment by oliver-zehentleitner** [comment]
:+1: 

sounds good!

**Comment by oliver-zehentleitner** [comment]
I added 

- Parameter `-- createconfigini` to cli interface
- Parameter `-- createprofilesini` to cli interface
- Parameter `-- openconfigini` to cli interface
- Parameter `-- openprofilesini` to cli interface 
- Parameter `-- example` to cli interface

With them i think its not necessary anymore...
